name: Teardown QA instance
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  schedule:
    - cron: "30 17 * * 5" # At 17.30 every Friday

  workflow_dispatch:

concurrency: terraform-qa

defaults:
  run:
    shell: bash

jobs:
  qa-down:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-central-1
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Load credentials from 1Password
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_GITHUB_TOKEN }}
          SLACK_WEBHOOK: op://CloudEng-General/Slack dfds.slack.com webhooks/jdm5vktylqnczrlkkbvsveyp5e
          AWS_ACCESS_KEY_ID: op://CloudEng-General/AWS account dfds-cloudengineering-bluep-nvfgm IAM user Deploy/username
          AWS_SECRET_ACCESS_KEY: op://CloudEng-General/AWS account dfds-cloudengineering-bluep-nvfgm IAM user Deploy/password

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: tests/qa

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: tests/qa

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -input=false -auto-approve
        working-directory: tests/qa

      - name: Cleanup CloudWatch Log Groups
        id: cloudwatch_log_groups
        run: ./cloudwatch_log_groups.sh
        working-directory: tests/qa

      - name: Send alert if job fails
        if: failure()
        uses: dfds/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ env.SLACK_WEBHOOK }}
          slack_message: Teardown QA environment for RDS failed.
